#----------------------------------------
#
# Workflow to make opkg package
#
#----------------------------------------

name: Make-opkg-package
env:
  OPENWRT_SDK_DIR: "openwrt-sdk-19.07.3-imx6_gcc-7.5.0_musl_eabi.Linux-x86_64"

on:
  push:
    branches: [ master ]

jobs:
  build-opkg-package:
    
    runs-on: ubuntu-18.04
    
    steps:

    - name: Install missing dependencies
      run: |
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe"
        #sudo apt-get update
        #sudo apt-get install libncurses5-dev       
        
    - name: Preparing, configuring and building the necessary tools using a precompiled SDK
      run: |
        curl -SL https://downloads.openwrt.org/releases/19.07.3/targets/imx6/generic/${{ env.OPENWRT_SDK_DIR}}.tar.xz | tar xJ
        cd ${{ env.OPENWRT_SDK_DIR}}
        ./scripts/feeds update -a
        ./scripts/feeds install libmosquitto
        make defconfig

    - name: Create package dir
      run: mkdir ${{ env.OPENWRT_SDK_DIR}}/package/VOYAGER-LINUX
      
    - name: Checks-out your repository
      uses: actions/checkout@v2
      with:
        path: ${{ env.OPENWRT_SDK_DIR}}/package/VOYAGER-LINUX
        
    - name: Compile OpenWrt project
      run: |
        cd ${{ env.OPENWRT_SDK_DIR}}
        make package/VOYAGER-LINUX/compile
