# This is a workflow to make opkg package

name: Make-opkg-package

on:
  push:
    branches: [ master ]

jobs:
  build-opkg-package:
    
    runs-on: ubuntu-18.4
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v2
      
    - name: apt-get update
      run: |
        sudo apt-get update
        sudo apt-get install gawk zlib1g libncurses5 g++ flex
        
        
    - name: Download and decompressing the SDK archive
      run: |
        echo Download and decompressing the SDK archive:
        curl -SL https://downloads.openwrt.org/releases/19.07.3/targets/imx6/generic/openwrt-sdk-19.07.3-imx6_gcc-7.5.0_musl_eabi.Linux-x86_64.tar.xz | tar xJ
        cd openwrt-sdk-19.07.3-imx6_gcc-7.5.0_musl_eabi.Linux-x86_64
        ./scripts/feeds update -a
        ./scripts/feeds install libmosquitto
        ls -la
        make defconfig
