# This is a workflow to make opkg package

name: Make-opkg-package

on:
  push:
    branches: [ master ]

jobs:
  build-opkg-package:
    
    runs-on: ubuntu-18.04
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v2
      
    - name: apt-get update
      run: |
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe"
        sudo apt-get update
        sudo apt-get install libncurses5-dev
        
        
    - name: Download and decompressing the SDK archive
      run: |
        echo Download and decompressing the SDK archive:
        curl -SL https://downloads.openwrt.org/releases/19.07.3/targets/imx6/generic/openwrt-sdk-19.07.3-imx6_gcc-7.5.0_musl_eabi.Linux-x86_64.tar.xz | tar xJ
        cd openwrt-sdk-19.07.3-imx6_gcc-7.5.0_musl_eabi.Linux-x86_64
        ./scripts/feeds update -a
        ./scripts/feeds install libmosquitto
        make defconfig
        git clone https://github.com/petroborys/VOYAGER-LINUX.git package/VOYAGER-LINUX
        ls -la
        
    - name: Compile
      run: |
        cd openwrt-sdk-19.07.3-imx6_gcc-7.5.0_musl_eabi.Linux-x86_64
        make package/VOYAGER-LINUX/compile
